use bdloja;

CREATE TABLE usuarios (
	usuario_id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL, 
	email VARCHAR(255) NOT NULL UNIQUE,   
	senha VARCHAR(255) NOT NULL, 
	cargo VARCHAR(100),    
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ativo BOOLEAN DEFAULT TRUE
);
